# Generated by Django 5.1.7 on 2025-04-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('organizer', 'Organizer'), ('volunteer', 'Volunteer')], default='user', max_length=20),
        ),
    ]
