# Generated by Django 5.2 on 2025-04-24 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('events', '0003_alter_registration_unique_together_and_more'),
        ('token_blacklist', '0012_alter_outstandingtoken_user'),
        ('users', '0003_customuser_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
