# Generated by Django 5.1.7 on 2025-04-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_customuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('organizer', 'Organizer'), ('admin', 'Admin'), ('volunteer', 'Volunteer')], default='user', max_length=50),
        ),
    ]
