# Generated by Django 4.2.20 on 2025-04-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('volunteer', 'Volunteer'), ('organizer', 'Organizer')], default='volunteer', max_length=50),
        ),
    ]
